// Code generated by mockery v2.9.4. DO NOT EDIT.

package usecase

import (
	usecase "github.com/khaliullov/coinbasevwap/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

// Match provides a mock function with given fields:
func (_m *UseCase) Match() usecase.MatchUseCase {
	ret := _m.Called()

	var r0 usecase.MatchUseCase
	if rf, ok := ret.Get(0).(func() usecase.MatchUseCase); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(usecase.MatchUseCase)
		}
	}

	return r0
}
